name: Forward PR Event to Dooray

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  notify:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Send full event payload to Dooray
        uses: actions/github-script@v6
        with:
          script: |
            const prTitle = context.payload.pull_request.title;
            const prDescription = context.payload.pull_request.body;

            // title과 description을 조합
            const combinedBody = `${prTitle}\n\n${prDescription}`;

            const payload = JSON.stringify({
              body: combinedBody,
              pr_url: context.payload.pull_request.html_url,
              author: context.payload.pull_request.user.login,
              merged_at: context.payload.pull_request.merged_at
            });

            const res = await fetch("https://nhnent.dooray.com/services/1708537454543641438/4056747660541074455/NaXDAyaQQ12Box37PL0kXQ", {
              method: "POST",
              headers: {
                "Content-Type": "application/json"
              },
              body: payload
            });
            const text = await res.text();
            console.log("Dooray response:", text);
